[project]
name = "python-engine"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.0",
    "httpx>=0.25.0",
    "librosa>=0.10.0",
    "mediapipe>=0.10.33",
    "numpy>=2.4.1",
    "pydantic>=2.13.0",
    "rapidfuzz>=3.13.0",
    "scipy>=1.16.0",
    "openai>=2.36.0"
]
